/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HachageFrame.java
 *
 * Created on 20 juin 2011, 15:48:54
 */
package hachagewallouf;

import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

/**
 *
 * @author a807087
 */
public class HachageFrame extends javax.swing.JFrame {

    /** Creates new form HachageFrame */
    public HachageFrame() {
        try {
            boolean find = false;
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    find = true;
                    break;
                }
            }
            if (!find) {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            }
        } catch (Exception e) {
        }
        initComponents();
        this.setTitle("Wallouf crypto");
        this.setVisible(true);
        this.jSplitPane1.setDividerLocation(0.5);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaUnCrypt = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCrypt = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Uncrypt text area -> Tape the uncrypted test here and copy the result on crypt text area");

        jTextAreaUnCrypt.setColumns(20);
        jTextAreaUnCrypt.setRows(5);
        jTextAreaUnCrypt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaUnCryptKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaUnCrypt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crypt text area -> Tape the Crypted test here and copy the result on Uncrypt text area");

        jTextAreaCrypt.setColumns(20);
        jTextAreaCrypt.setRows(5);
        jTextAreaCrypt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaCryptKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaCrypt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        jMenu1.setText("File");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        jMenuItem1.setText("Erase all");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAreaUnCryptKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaUnCryptKeyReleased
        String uncrypt = jTextAreaUnCrypt.getText();
        String crypt = "";
        if (!uncrypt.isEmpty()) {
            for (int i = 0; i < uncrypt.length(); i++) {
                char c = uncrypt.charAt(i);
                //Majuscules
                if ((int) c > 64 && (int) c < 91) {
                    if (((int) (c / 13) % 2) != 0) {
                        crypt += (char) (c + 13);
                    } else {
                        crypt += (char) (c - 13);
                    }
                    //minuscules
                } else if ((int) c > 96 && (int) c < 123) {
                    if (((int) (c / 13) % 2) != 0) {
                        crypt += (char) (c + 13);
                    } else {
                        crypt += (char) (c - 13);
                    }
                } else if ((int) c > 191 && (int) c < 240) {
                    System.out.println("R 192:"+((192/13)%2));
                    System.out.println("R 239:"+((239/13)%2));
                    if (((int) (c / 13) % 2) != 0) {
                        crypt += (char) (c + 13);
                    } else {
                        crypt += (char) (c - 13);
                    }
                } else {
                    crypt += (char) (c);
                }
            }
            jTextAreaCrypt.setText(crypt);
        }
    }//GEN-LAST:event_jTextAreaUnCryptKeyReleased
// 192 a 239
    private void jTextAreaCryptKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaCryptKeyReleased
        String uncrypt = jTextAreaCrypt.getText();
        String crypt = "";
        if (!uncrypt.isEmpty()) {
            for (int i = 0; i < uncrypt.length(); i++) {
                char c = uncrypt.charAt(i);
                //Majuscules
                if ((int) c > 64 && (int) c < 91) {
                    if (((int) (c / 13) % 2) != 0) {
                        crypt += (char) (c + 13);
                    } else {
                        crypt += (char) (c - 13);
                    }
                } else if ((int) c > 109 && (int) c < 117 || (int) c > 129 && (int) c < 136) {
                    crypt += (char) (c - 13);
                } else if ((int) c > 90 && (int) c < 104) {
                    crypt += (char) (c + 13);
                } else if ((int) c > 204 && (int) c < 253) {
                    if (((int) (c / 13) % 2) != 0) {
                        crypt += (char) (c + 13);
                    } else {
                        crypt += (char) (c - 13);
                    }
                } else {
                    crypt += (char) (c);
                }
            }
            jTextAreaUnCrypt.setText(crypt);
        }
    }//GEN-LAST:event_jTextAreaCryptKeyReleased

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jTextAreaUnCrypt.setText("");
        jTextAreaCrypt.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextAreaCrypt;
    private javax.swing.JTextArea jTextAreaUnCrypt;
    // End of variables declaration//GEN-END:variables
}
